#!/usr/bin/env ruby

$group_size = ARGV[0].split('=').last.to_i

require 'json'
require 'tsort'

file = $stdin
file = File.open(ARGV[1]) if ARGV[1]

all_friends = JSON.load(file.read)


require 'tsort'

class Hash
  include TSort
  alias tsort_each_node each_key

  def tsort_each_child(node, &block)
    likes = self[node]
    return unless likes
    likes.each(&block)
  end
end

graph = {}

all_friends.each do |friendship|
  graph[friendship.first] ||= []
  graph[friendship.first] << friendship.last
end

groups = graph.strongly_connected_components.select { |x| x.length >= $group_size }
puts groups.to_json
